### ISSUE TITLE
Profile Image Click

### ISSUE THREAD

**Issue by maine98** [shivanshtalwar0/chatbar#1]
Hi, is there a method that allows me to perform an action on the click of the profile image? Thank you and good job

**Comment by shivanshtalwar0** [comment]
I haven't added that yet will add it soon stay tuned, until then you could
look into source code and wrap the profile image part in gesture detector
widget to listen for image tap event to show profile image

**Comment by shivanshtalwar0** [comment]
Added support that you were asking for
